#服务端
server:
  port: 8181
  tomcat:
    uri-encoding: utf-8

#框架
spring:

  # 数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 127.0.0.1
    password:
    database: 0
    timeout: 0
    jedis:
      pool:
        max-active: -1
        max-idle: 10
        min-idle: 2
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  # 邮件
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jianzhong.demo.domain
