#服务端
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#框架
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        max-wait: 300

  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  # 邮件
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
    default-encoding: UTF-8

#数据库持久层
mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
  type-aliases-package: com.jianzhong.demo.domain
  config-location: classpath:/mybatis/config/mybatis-config.xml

#日志
logging:
  file: /data/jianzhong/springboot/demo/src/main/resources/logs/error.log
  level:
    root: error
    com.jianzhong.demo: info

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
